# Generated by Django 4.1.7 on 2023-03-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecom.shippingaddress'),
            preserve_default=False,
        ),
    ]
