# Generated by Django 4.1.7 on 2023-03-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_orders_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.IntegerField()),
                ('vendor_code', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecom.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecom.products')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecom.promo'),
            preserve_default=False,
        ),
    ]
