# Generated by Django 4.1.7 on 2023-03-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_aboutinfo_helpinfo_keyboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ecom.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='tegs',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
